### ISSUE TITLE
Final Checklist

### ISSUE THREAD

**Issue by kellydhunter1** [kellydhunter1/Picto-Plots-v2#4]
- [x]  Render plot of movie
- [x]  Show picture thumbnails that represent the plot
- [x]  Show word represented on mouseover of picture
- [x]  New play with another movie from the list
